### ISSUE TITLE
Add option to export as sprite sheet

### ISSUE THREAD

**Issue by PKGaspi** [PKGaspi/AsepriteScripts#1]
When exporting as .png, it can be useful to export multiple frames as a sprite sheet instead of as many images.

**Comment by knightofiam** [comment]
I'm not sure if this is the same idea, but exporting layers as individual files does not work for me because I want all frames / animation tags for a single layer included in the same png file. Right now I still have to manually export every single layer into its own sprite sheet.

**Comment by PKGaspi** [comment]
yes, it's the same idea this issue refers to.

**Comment by knightofiam** [comment]
Thanks for fixing! Looking forward to testing it out. It’s a huge time saver when dealing with a lot of layers.

**Comment by knightofiam** [comment]
@PKGaspi It works for layers-as-spritesheets, but you have to click Cancel or the X like 30 times (once per layer). Is there a way to fully automate this?

<img width="1222" alt="Screen Shot 2022-01-22 at 6 27 59 AM" src="https://user-images.githubusercontent.com/72765293/150638657-6cfb3145-562f-458a-8840-03b888bf912c.png">

**Comment by PKGaspi** [comment]
I'm sorry, I've left some debugging code in there. I'll fix it in a moment.

**Comment by knightofiam** [comment]
It seems to be working correctly now, thanks again!
