### ISSUE TITLE
bad argument error in Unsaved projects

### ISSUE THREAD

**Issue by Jalkhov** [PKGaspi/AsepriteScripts#2]
When trying to use some of the options
```
export_combinations
export_layers
export_slices
```
in projects that have not been saved for the first time throws the following error:
![Screenshot_1](https://user-images.githubusercontent.com/36505934/148586998-2f32943b-5b09-4eb6-9956-b9cbf5f760d2.png)
Of course it is not something that prevents the script from working, you can save the project and that's it, I just wanted to raise awareness of the issue.

**Comment by PKGaspi** [comment]
Thanks for the report. It's intended behaviour that the script doesn't work for unsaved files, but there should be an error message telling so.
