### ISSUE TITLE
Groups are not set to visible during export layers

### ISSUE THREAD

**Issue by nihiluis** [PKGaspi/AsepriteScripts#5]
If a group is not visible during export_layers, the associated exported layers will be empty files.

**Comment by PKGaspi** [comment]
Hey, thanks for issuing about this. Can you please provide the following information?

- Aseprite version.
- Affected script(s).
- Expected behaviour.

Thank you!

**Comment by nihiluis** [comment]
v1-x.dev (this should be a git clone)
its the export_layers script as specified. 
expected behavior is that the output files will have the respective layer's content exported regardless of the associated group(s) being invisible.
similar to how the layers are set to visible before the respective export, the groups should be set to visible (and invisible afterwards) as well.

**Comment by PKGaspi** [comment]
Alright, it should be up and working on main. Probably this behaviour was affected by some change in an Aseprite update. Thanks for reporting again and sorry for the delay!
