### ISSUE TITLE
When exporting slices, the background color changes

### ISSUE THREAD

**Issue by yallspark** [PKGaspi/AsepriteScripts#7]
This is how I have the image, numbers separated by slices
![image](https://user-images.githubusercontent.com/104654578/189485429-eee4acc5-4b08-494c-8d42-f9f06ac4691c.png)

After Exporting it looks like this:
![image](https://user-images.githubusercontent.com/104654578/189485469-5ad1e912-6997-4904-8fb2-550a4f10c705.png)

First Slice worked fine, all the rest have the background color changed:
![image](https://user-images.githubusercontent.com/104654578/189485489-cd91169c-7936-457a-baf6-b73566d454d9.png)

**Comment by PKGaspi** [comment]
Hey, thanks for submitting the issue. Can you please provide the following?

- Aseprite version or commit
- A test .ase file to verify and reproduce the issue

**Comment by yallspark** [comment]
Apologies on the delay, new to GitHub! [Google Drive Link](https://drive.google.com/file/d/1ewMFlWh1KCJD_HfTpWcixr3hSElm6eiR/view?usp=sharing)

My canvas size was bigger maybe and that might have caused some issues? I shrunk it down and it worked just now... Maybe I was selecting it strangely?

**Comment by PKGaspi** [comment]
Hey, I've just requested access to the file you provided :)

**Comment by yallspark** [comment]
Accepted!

**Comment by PKGaspi** [comment]
I'm not sure on how to replicate this. The file I received has a black background layer, which doesn't correspond to the green layer that you show in the issue.

**Comment by PKGaspi** [comment]
Closing as I can't reproduce
