### ISSUE TITLE
Change folder structure to allow easy cloning and pulling

### ISSUE THREAD

**Issue by douglaslassance** [PKGaspi/AsepriteScripts#8]
The current folder structure of the repository means one cannot simply clone it in `Aseprite\scripts` and pull future updates easily. The root of the repository should be the `scripts/gaspi` folder.

**Comment by PKGaspi** [comment]
Hey! Thanks for submitting the issue. However, I don't really know what's the problem here. I have the repo cloned in my scripts folder and the scripts appear in Aseprite as expected. Can you elaborate a little farther?

**Comment by douglaslassance** [comment]
If I cloned your repository in my `scripts` folder, the resulting path for me would be `%APPDATA%\Aseprite\scripts\AseScripts\scripts\gaspi`. I was proposing that `%APPDATA%\Aseprite\scripts\AseScripts` would be better given the wrong assumption that the first path would not detect the scripts preventing to clone your repository directly into the `scripts` folder.

Now that you made me realize that Aseprite will dig into sub-folders to find the scripts, this becomes just a matter of how the path would look more so than actual functionality. As you can see below, it creates a lot more sub-menus than ideally required.

![unnamed-2](https://user-images.githubusercontent.com/1711423/202523438-a597a44a-018a-4cbb-875e-5ad0669851fd.png)

Feel free to close this issue if you don't think that aspect is relevant.

**Comment by PKGaspi** [comment]
I know the submenus are not the best for a quick workflow, but it prevents the possibility of other scripts overwritting mine in the future if they have the same name. Also, my scripts are thought for more ocassional usage, plus you can always asign it a hotkey (I recall).

Thanks for the suggestion anyways, I will close this now.

**Comment by douglaslassance** [comment]
Well, you still clone to a folder in `scripts` right? Your repository is called 
`AsepriteScripts`. I would simply clone it as `GaspiAsepriteScripts` or whatever has no chance to create conflicts.
